### ISSUE TITLE
jdk14?

### ISSUE THREAD

**Issue by viqtor** [dadoonet/elasticsearch-beyonder#179]
whats the reasoning behind moving this to jdk14? #161 for reference.
according to [support matrix](https://www.elastic.co/support/matrix#matrix_jvm) elastic still supports jdk8 in the most recent version where jdk14 isn't officially listed as supported in 7.13

**Comment by dadoonet** [comment]
I just wanted to remove java8 from this project as IMO it should not be used anymore in production.

Is that an issue on your side?
