### ISSUE TITLE
Add support for aliases

### ISSUE THREAD

**Issue by dadoonet** [dadoonet/elasticsearch-beyonder#2]
In Spring elasticsearch project, we were supporting aliases. We should try to support that here as well.

**Comment by gammaliu** [comment]
How to create aliases? I can't find example in the README.

**Comment by dadoonet** [comment]
Not implemented within beyonder but only supported in Spring project: https://github.com/dadoonet/spring-elasticsearch#creating-aliases-to-indexes

**Comment by dadoonet** [comment]
I think that the best way to support this for now is by using index templates.

**Comment by dadoonet** [comment]
I think we should add the support for it https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html

And watch files in `_aliases` dir like we do for index templates and pipelines. That would help to support https://github.com/dadoonet/spring-elasticsearch/issues/36
