### ISSUE TITLE
Multiple classpath entries problem

### ISSUE THREAD

**Issue by magaton** [dadoonet/elasticsearch-beyonder#31]
Hello, thanks for the project. Very handy!
I have a problem in my "monolith" app which includes module1 and module2 as dependencies.
module1 has src/main/resources/elasticsearch/people with _settings.json and person.json (type) 
module2 has src/main/resources/elasticsearch/items with _settings.json and item.json (type) 

When monolith app starts up only src/main/resources/elasticsearch/people has been discovered. 
people index is correctly created.
module2 with src/main/resources/elasticsearch/items has been completely ignored.

If I remove module1 (with people) from monolith pom, I can see that module2  with src/main/resources/elasticsearch/items has been picked up and index is created.

I would suspect that discovery stops after 1st resource (elasticsearch dir) is found. 
Would you consider this behavior asa bug or do you have some suggestion for a workaround?

Milan

**Comment by dadoonet** [comment]
Yeah that's true. As a workaround, I'd recommend using 2 different folders in the classpath ie `es1` and `es2` instead of `elasticsearch`, then call beyonder with:

Project 1:

```java
ElasticsearchBeyonder.start(client, "models/es1");
```

Project 2:

```java
ElasticsearchBeyonder.start(client, "models/es2");
```

Would that work?

**Comment by dadoonet** [comment]
I'm closing as we found I believe the best workaround.
