### ISSUE TITLE
Not clear from readme what this project is

### ISSUE THREAD

**Issue by Harvzor** [dadoonet/elasticsearch-beyonder#53]
I came to this repo from https://stackoverflow.com/questions/43203132/elasticsearch-schema-migrations.

After reading the `readme.md` for a couple of minutes, I'm still not sure what this project does. All I know is how to set it up.

Probably it needs a short description such as:

>Elasticsearch Beyonder is a an ElasticSearch plugin which helps with managing schema migrations for .NET applications

Though I'm not sure if this is even correct.

Thanks.

**Comment by dadoonet** [comment]
It's incorrect.
It's a java project. It creates automatically a schema at startup if it does not exist yet.
Nothing fancy or smart here.
