### ISSUE TITLE
Is it possible to update mapping?

### ISSUE THREAD

**Issue by nilskuhn** [dadoonet/elasticsearch-beyonder#92]
Hi there,

first: Thanks for your great work!

I am wondering whether it's possible to update mapping of an existing index. The readme is not clear about that. 

I tried start parameters, but `force` seems to always delete old index before creating new one. I supposed `merge` could be a parameter that updates given index (if possible).  
```
ElasticsearchBeyonder.start(restClient.lowLevelRest(), "elasticsearch", true, false);
```
But dosn't seem so. I tried to add a new field to my mapping json file, but it isn't created on startup (of my Spring Boot application leveraging beyonder.

So doesn't beyonder support updating mapping of existing indices? And if so: Is this intentional?

I think this is very important. Otherwise I would have to create a new index with **every** change (and re-index all data). That would be annoying and for me it would be a reason not to use beyonder, I think.

Regards and thanks in advance for an answer.

**Comment by dadoonet** [comment]
Hey

Beyonder might be able to update an index if you provide a file named `_update_settings.json` or maybe `INDEX_update_settings.json`.

But I deprecated this option a long time ago IIRC so it's only available with the TransportClient.
is that something you need for the RestClient? If so we need to remove the deprecation and implement this feature for the RestClient.

PR are always welcomed 😄

**Comment by nilskuhn** [comment]
Yes, I would need it for RestClient. I would really like to get involved. Only time is limited... ;)
Probably I will use `spring-data-elasticsearch`s Entity classes with Annotations to create/update indices for the moment (hopefully updates will get applied to existing indices if possible).

If I find some time later on (if project stress eases somewhat) maybe I will have a look.
And don't misunderstand: Many thanks for the project and sharing!

**Comment by dadoonet** [comment]
I was looking at this today and I can see in the code that this is actually supported but not documented.

Add a file named `_update_settings.json` in the index directory should do the job for both Transport and Rest clients.
I will check if I should add this to the documentation.

**Comment by dadoonet** [comment]
After further checking, `_update_settings` file can actually only update settings and not mappings.
